config/routes.rb
Rails.application.routes.draw do
  root 'landings#home'
  resources :posts, except: %i[edit update] do
    resources :likes, only: %i[index], module: 'posts'
    resources :comments, except: %i[show edit update], module: 'posts'
  end
  get 'comments/:id/likes', to: 'comments/likes#index', as: 'comment_likes'
  resources :users, only: %i[index show] do
    resources :friends, only: %i[index], controller: 'friendships'
  end
  resources :friends, only: %i[create update destroy], controller: 'friendships', as: 'friendships'
  resources :notifications, only: %i[index destroy]
  put 'notifications/:id', to: 'notifications#update_hidden', as: 'update_notification_hidden'
  post '/users/notifications-seen', to: 'users#notifications_seen'
  resources :likes, only: %i[create destroy]

  devise_for :users, path: 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                                      registrations: 'users/registrations',
                                                      sessions: 'users/sessions',
                                                      passwords: 'users/passwords' }
  devise_scope :user do
    get '/accounts/complete', to: 'users/registrations#complete_edit'
    put '/accounts/complete', to: 'users/registrations#complete_update'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :notifications, as: :notificationable, dependent: :destroy
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :content, presence: true
end

app/controllers/comments/likes_controller.rb
class Comments::LikesController < ApplicationController
  before_action :check_authorization, only: %i[index]

  def index
    @users = User.joins(:likes).where('likes.likeable_type = ? AND likes.likeable_id = ?', 'Comment', params[:id])
    render 'likes/index'
  end

  private

  # Allow showing likes only of
  #   - comments that belong to posts whose author is the current_user or one of current_user's friends
  def check_authorization
    comment_post_author = Comment.find(params[:id]).post.author
    allow_create = false
    allowed_list = current_user.friends.to_a << current_user
    allow_create = true if allowed_list.include?(comment_post_author)
    return if allow_create

    redirect_back_or_to root_path, status: :forbidden
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_authorization_for_destroy, only: %i[destroy]
  before_action :check_authorization_for_other_actions, except: %i[destroy]

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        unless current_user == @comment.post.author
          Notification.create(notificationable_id: @comment.id,
                              notificationable_type: 'Comment',
                              user_id: @comment.post.author.id,
                              content: "#{current_user.first_name} #{current_user.last_name} has commented on your post",
                              path: post_path(@comment.post))
        end
        format.turbo_stream
        format.html { redirect_back_or_to post_comments_path(@comment.post) }
      else
        flash[:error] = 'Invalid Comment'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def check_authorization_for_other_actions
    post = Post.find(params[:post_id])
    return if post.author == current_user || post.author.friends.exists?(id: current_user.id)

    redirect_back_or_to root_path, status: :forbidden
  end

  def check_authorization_for_destroy
    comment = Comment.find(params[:id])
    return if comment.author == current_user || comment.post.author == current_user

    flash[:error] = 'You are not authorized to delete this comment'
    redirect_back_or_to root_path, status: :forbidden
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  before_action :check_authorization_for_destroy, only: %i[destroy]
  before_action :check_authorization_for_other_actions, except: %i[destroy]

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        unless current_user == @comment.post.author
          notification = create_notification(@comment)
          broadcast_notification(notification)
        end
        format.turbo_stream
        format.html { redirect_back_or_to post_comments_path(@comment.post) }
      else
        flash[:error] = 'Invalid Comment'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def check_authorization_for_other_actions
    post = Post.find(params[:post_id])
    return if post.author == current_user || post.author.friends.exists?(id: current_user.id)

    redirect_back_or_to root_path, status: :forbidden
  end

  def check_authorization_for_destroy
    comment = Comment.find(params[:id])
    return if comment.author == current_user || comment.post.author == current_user

    flash[:error] = 'You are not authorized to delete this comment'
    redirect_back_or_to root_path, status: :forbidden
  end

  def create_notification(comment)
    Notification.create(notificationable_id: comment.id,
                        notificationable_type: 'Comment',
                        user_id: comment.post.author.id,
                        content: "#{current_user.first_name} #{current_user.last_name} has commented on your post",
                        path: "#{post_path(comment.post.id)}#comment_#{comment.id}")
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :check_authorization, only: %i[index]

  def index
    @users = User.joins(:likes).where('likes.likeable_type = ? AND likes.likeable_id = ?', 'Post', params[:post_id])
    render 'likes/index'
  end

  private

  # Allow showing likes only of
  #   - comments that belong to posts whose author is the current_user or one of current_user's friends
  def check_authorization
    post_author = Post.find(params[:post_id]).author
    allow_create = false
    allowed_list = current_user.friends.to_a << current_user
    allow_create = true if allowed_list.include?(post_author)
    return if allow_create

    redirect_back_or_to root_path, status: :forbidden
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_authorization_for_destroy, only: %i[destroy]
  before_action :check_authorization_for_show, only: %i[show]
  def index
    friends_ids = Friendship.where(user_id: current_user.id, status: 2).pluck(:friend_id)
    @post = Post.new
    @posts = Post.where(user_id: current_user.id)
                 .or(Post.where(user_id: friends_ids))
                 .order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.turbo_stream
        format.html { redirect_back_or_to root_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    path = post_url(@post)
    @post.destroy
    respond_to do |format|
      format.turbo_stream
      if request.referer == path
        format.html { redirect_to root_path }
      else
        format.html { redirect_back_or_to root_path }
      end
    end
  
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def check_authorization_for_destroy
    post = Post.find(params[:id])
    return if post.author == current_user

    flash[:error] = 'You are not authorized to delete this post'
    redirect_back_or_to root_path, status: :forbidden
  end

  def check_authorization_for_show
    post = Post.find(params[:id])
    return if post.author == current_user || post.author.friends.exists?(id: current_user.id)

    redirect_back_or_to root_path, status: :forbidden
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/comments/_comment.html.erb
<div id=<%= "comment_#{comment.id}" %> class='comment'>
  <%= simple_format h comment.content %>
  <div class='comment-info-and-interactions'>
    <%= render 'shared/resource_info', resource: comment %>
    <div class='comment-interactions'>
      <div id=<%= "Comment_#{comment.id}_likes" %>>
        <% if Like.where(user_id: current_user.id, likeable_type: 'Comment', likeable_id: comment.id).exists? %>
          <%= link_to like_path(comment.likes.find_by(user_id: current_user.id).id), data: { turbo_method: :delete }, class: 'comment-unlike-link' do %>
            <span class="material-symbols-outlined like-symbol">
              Like
            </span>
          <% end %>
        <% else %>
          <%= form_with model: Like.new(), url:likes_path do |form| %>
            <%= form.hidden_field :likeable_type, value: 'Comment' %>
            <%= form.hidden_field :likeable_id, value: comment.id %>
            <label>
              <%= form.submit '', class: 'comment-like-submit' %>
              <button class='like-button'>
                <span class="material-symbols-outlined like-symbol">
                  Like
                </span>
              </button>
            </label>
          <% end %>
        <% end %>
      </div>
      <div id=<%= "Comment_#{comment.id}_likes_counter" %> class='likes-counter-div'>
        <%= link_to comment.likes.size, comment_likes_path(comment), class:'likes-counter-link' , data: { turbo_frame: "_top" } %>
      </div>
    </div>
  </div>
  <% if current_user == comment.author || current_user == comment.post.author %>
    <%= link_to post_comment_path(comment.post, comment), data: { turbo_method: :delete }, class: 'comment-delete-link' do %>
      <span class="material-symbols-outlined">
        Delete
      </span>
    <% end %>
  <% end %>
</div>

app/views/posts/comments/_comment_form.html.erb
<%= form_with model: comment, url: [comment.post, comment], class: 'comment-form' do |form| %>
  <%= form.text_area :content, placeholder: 'Comment here', id: 'comment_text' %>
  <%= form.hidden_field :post_id, value: comment.post_id %>
  <%= form.submit 'Comment', class: 'comment-form-button' %>
<% end %>

app/views/posts/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments_post_#{@comment.post.id}", @comment %>
<%= turbo_stream.update "turbo_frame_tag_post_#{@comment.post.id}" do %>
    <%= turbo_frame_tag id='new_comment', src: new_post_comment_path(@comment.post) %>
<% end %>
<%= turbo_stream.update "post_#{@comment.post.id}_comments_counter" do %>
  <span class="material-symbols-outlined comment-symbol comment-symbol-active" data-action='click->comments#toggle keydown.enter->comments#toggle' data-comments-target='commentSymbol' tabindex='0'>
    Comment
  </span>
  <span class='comments-counter-span'>
    <%= @comment.post.comments.size %>
  </span>
<% end %>

app/views/posts/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>
<%= turbo_stream.update "post_#{@comment.post.id}_comments_counter" do %>
  <span class="material-symbols-outlined comment-symbol comment-symbol-active" data-action='click->comments#toggle keydown.enter->comments#toggle' data-comments-target='commentSymbol' tabindex='0'>
    Comment
  </span>
  <span class='comments-counter-span'>
    <%= @comment.post.comments.size %>
  </span>
<% end %>

app/views/posts/comments/index.html.erb
<%= turbo_frame_tag id='comments' do %>
  <div id=<%= "comments_post_#{@post.id}"%> class ='comments'>
    <%= render @comments %>
  </div>
<% end %>
<div id=<%= "turbo_frame_tag_post_#{@post.id}"%>>
  <%= turbo_frame_tag id='new_comment', src: new_post_comment_path(@post) %>
</div>

app/views/posts/comments/new.html.erb
<%= turbo_frame_tag id='new_comment' do %>
  <% if @comment.errors.any? %>
    <div id='error_explaination'>
      <h3>Errors:</h3>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'comment_form', comment: @comment %>
<% end %>