config/routes.rb
Rails.application.routes.draw do
  root 'landings#home'
  resources :posts, except: %i[edit update] do
    resources :likes, only: %i[index], module: 'posts'
    resources :comments, except: %i[show edit update], module: 'posts'
  end
  get 'comments/:id/likes', to: 'comments/likes#index', as: 'comment_likes'
  resources :users, only: %i[index show] do
    resources :friends, only: %i[index], controller: 'friendships'
  end
  resources :friends, only: %i[create update destroy], controller: 'friendships', as: 'friendships'
  resources :notifications, only: %i[index destroy]
  put 'notifications/:id', to: 'notifications#update_hidden', as: 'update_notification_hidden'
  post '/users/notifications-seen', to: 'users#notifications_seen'
  resources :likes, only: %i[create destroy]

  devise_for :users, path: 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                                      registrations: 'users/registrations',
                                                      sessions: 'users/sessions',
                                                      passwords: 'users/passwords' }
  devise_scope :user do
    get '/accounts/complete', to: 'users/registrations#complete_edit'
    put '/accounts/complete', to: 'users/registrations#complete_update'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notificationable, polymorphic: true
  validates :content, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :check_authorization, except: %i[index]

  def index
    @notifications = current_user.notifications.order(created_at: :desc)
  end

  def update_hidden
    @notification = Notification.find(params[:id])
    @notification.update(hidden: true)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path }
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path }
    end
  end

  private

  def check_authorization
    notification = Notification.find(params[:id])
    return if notification.user_id == current_user.id

    flash[:error] = 'You are not authorized to perform this action'
    redirect_back_or_to root_path, status: :forbidden
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  # returns the user who has triggered the notification
  def notification_triggerer(notification)
    n14e = notification.notificationable
    if n14e.instance_of?(Friendship)
      if n14e.status == 1
        n14e.requested
      else
        n14e.requester
      end
    elsif n14e.instance_of?(Like)
      n14e.user
    elsif n14e.instance_of?(Comment)
      n14e.author
    end
  end

  def recent_notifications
    n = current_user.notifications.where('created_at > ?', current_user.notifications_viewed_at).size
    if n > 5
      current_user.notifications.where('created_at > ?', current_user.notifications_viewed_at).order(created_at: :desc)
    else
      current_user.notifications.where(hidden: false).order(created_at: :desc).first(5)
    end
  end
end

app/views/notifications/_notification.html.erb
<div id=<%= "notification_#{ notification.id }" %>>
  <%= link_to notification.content, notification.path %>
   - 
  <%= content_tag :span, notification.created_at.strftime('%d %b %Y - %H:%M') %>
   - 
   <%= link_to 'Delete notification', notification, data: { turbo_method: 'delete' } %>
</div>

app/views/notifications/_recent_notification.html.erb
<%= content_tag :div, id: "recent_notification_#{n.id}", class: 'notification' do %>
  <%= link_to n.path, class: 'notification-info' do %>
    <%= image_tag notification_triggerer(n).avatar.variant(:thumb), class: 'notification-avatar' %>
    <div class='notification-text-and-date'>
      <%= content_tag :p, n.content, class: 'notification-text' %>
      <%= content_tag :div, n.created_at.strftime('%d %b %Y - %H:%M'), class: 'notification-date' %>
    </div>
  <% end %>
  <%= form_with url: update_notification_hidden_path(n), method: 'put', class: 'notification-hide-form' do |form| %>
    <%= form.submit '', class: 'notification-hide-button' %>
  <% end %>
<% end %>

app/views/notifications/destroy.turbo_stream.erb
<%= turbo_stream.remove "recent_notification_#{@notification.id}" %>
<%= turbo_stream.remove "notification_#{@notification.id}" %>

app/views/notifications/index.html.erb
<h1>My notifications</h1>

<%= render @notifications %>

app/views/notifications/update_hidden.turbo_stream.erb
<%= turbo_stream.remove "recent_notification_#{@notification.id}" %>