config/routes.rb
Rails.application.routes.draw do
  root 'landings#home'
  resources :posts, except: %i[edit update] do
    resources :likes, only: %i[index], module: 'posts'
    resources :comments, except: %i[show edit update], module: 'posts'
  end
  get 'comments/:id/likes', to: 'comments/likes#index', as: 'comment_likes'
  resources :users, only: %i[index show] do
    resources :friends, only: %i[index], controller: 'friendships'
  end
  resources :friends, only: %i[create update destroy], controller: 'friendships', as: 'friendships'
  resources :notifications, only: %i[index destroy]
  put 'notifications/:id', to: 'notifications#update_hidden', as: 'update_notification_hidden'
  post '/users/notifications-seen', to: 'users#notifications_seen'
  resources :likes, only: %i[create destroy]

  devise_for :users, path: 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                                      registrations: 'users/registrations',
                                                      sessions: 'users/sessions',
                                                      passwords: 'users/passwords' }
  devise_scope :user do
    get '/accounts/complete', to: 'users/registrations#complete_edit'
    put '/accounts/complete', to: 'users/registrations#complete_update'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :content, presence: true
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  before_action :check_authorization_for_destroy, only: %i[destroy]
  before_action :check_authorization_for_other_actions, except: %i[destroy]

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        unless current_user == @comment.post.author
          notification = create_notification(@comment)
          broadcast_notification(notification)
        end
        format.turbo_stream
        format.html { redirect_back_or_to post_comments_path(@comment.post) }
      else
        flash[:error] = 'Invalid Comment'
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back_or_to root_path }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def check_authorization_for_other_actions
    post = Post.find(params[:post_id])
    return if post.author == current_user || post.author.friends.exists?(id: current_user.id)

    redirect_back_or_to root_path, status: :forbidden
  end

  def check_authorization_for_destroy
    comment = Comment.find(params[:id])
    return if comment.author == current_user || comment.post.author == current_user

    flash[:error] = 'You are not authorized to delete this comment'
    redirect_back_or_to root_path, status: :forbidden
  end

  def create_notification(comment)
    Notification.create(notificationable_id: comment.id,
                        notificationable_type: 'Comment',
                        user_id: comment.post.author.id,
                        content: "#{current_user.first_name} #{current_user.last_name} has commented on your post",
                        path: "#{post_path(comment.post.id)}#comment_#{comment.id}")
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :check_authorization, only: %i[index]

  def index
    @users = User.joins(:likes).where('likes.likeable_type = ? AND likes.likeable_id = ?', 'Post', params[:post_id])
    render 'likes/index'
  end

  private

  # Allow showing likes only of
  #   - comments that belong to posts whose author is the current_user or one of current_user's friends
  def check_authorization
    post_author = Post.find(params[:post_id]).author
    allow_create = false
    allowed_list = current_user.friends.to_a << current_user
    allow_create = true if allowed_list.include?(post_author)
    return if allow_create

    redirect_back_or_to root_path, status: :forbidden
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_authorization_for_destroy, only: %i[destroy]
  before_action :check_authorization_for_show, only: %i[show]
  def index
    friends_ids = Friendship.where(user_id: current_user.id, status: 2).pluck(:friend_id)
    @post = Post.new
    @posts = Post.where(user_id: current_user.id)
                 .or(Post.where(user_id: friends_ids))
                 .order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.turbo_stream
        format.html { redirect_back_or_to root_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    path = post_url(@post)
    @post.destroy
    respond_to do |format|
      format.turbo_stream
      if request.referer == path
        format.html { redirect_to root_path }
      else
        format.html { redirect_back_or_to root_path }
      end
    end
  
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def check_authorization_for_destroy
    post = Post.find(params[:id])
    return if post.author == current_user

    flash[:error] = 'You are not authorized to delete this post'
    redirect_back_or_to root_path, status: :forbidden
  end

  def check_authorization_for_show
    post = Post.find(params[:id])
    return if post.author == current_user || post.author.friends.exists?(id: current_user.id)

    redirect_back_or_to root_path, status: :forbidden
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div id=<%= "post_#{post.id}" %> class='post' data-controller='comments' >
  <div class='post-content-and-interactions'>
    <div class='post-content'><%= simple_format h post.content %></div>
    <div class='post-info-and-interactions'>
      <%= render 'shared/resource_info', resource: post %>
      <div class='post-interactions'>
        <div id=<%= "Post_#{post.id}_likes" %>>
          <% if Like.where(user_id: current_user.id, likeable_type: 'Post', likeable_id: post.id).exists? %>
            <%= link_to like_path(post.likes.find_by(user_id: current_user.id).id), data: { turbo_method: :delete }, class: 'post-unlike-link'  do %>
              <span class="material-symbols-outlined like-symbol">
                Like
              </span>
            <% end %>
          <% else %>
            <%= form_with model: Like.new(), url:likes_path do |form| %>
              <%= form.hidden_field :likeable_type, value: 'Post' %>
              <%= form.hidden_field :likeable_id, value: post.id %>
              <label>
                <%= form.submit '', class: 'post-like-submit' %>
                <button class='like-button'>
                  <span class="material-symbols-outlined like-symbol">
                    Like
                  </span>
                </button>
              </label>
            <% end %>
          <% end %>
        </div>
        <div id=<%= "Post_#{post.id}_likes_counter"%> class='likes-counter-div'>
          <%= link_to post.likes.size, post_likes_path(post), class:'likes-counter-link' %>
        </div>
        <div id=<%= "post_#{post.id}_comments_counter" %>>
          <span class="material-symbols-outlined comment-symbol" data-action='click->comments#toggle keydown.enter->comments#toggle' data-comments-target='commentSymbol' tabindex='0'>
            Comment
          </span>
          <span class='comments-counter-span'>
            <%= post.comments.size %>
          </span>
        </div>
      </div>
    </div>
    <% if post.author == current_user %>
      <%= link_to post_path(post.id), data: { turbo_method: 'delete' }, class: 'post-delete-link' do %>
        <span class="material-symbols-outlined">
          Delete
        </span>     
      <% end %>
    <% end %>
  </div>
  <div class='post-comments' data-comments-target='postComments'>
    <div id=<%= "turbo_frame_tag_post_#{post.id}" %>>
      <%= turbo_frame_tag id='new_comment', src: new_post_comment_path(post) %>
    </div>
    <%= turbo_frame_tag id='comments', src: post_comments_path(post) %>
  </div>
</div>

app/views/posts/_post_form.html.erb
<%= form_with model: post, id: 'post_form' do |form| %>
  <%= form.text_area :content, placeholder: "Tell the world what you're thinking", class: 'new-post-textbox' %>
  <br>
  <%= form.submit 'Post', class: 'post-form-button' %>
<% end %>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend 'posts', @post %>
<%= turbo_stream.remove 'error_explanation' %>
<%= turbo_stream.replace 'post_form' do %>
  <%= render partial: 'post_form', locals: { post: Post.new } %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove "post_#{@post.id}" %>

app/views/posts/index.html.erb
<div class='posts-container'>
  <div class='posts-form-and-index'>
    <h2>New post</h2>
    <%= turbo_frame_tag id='new_post', src:new_post_path %>

    <h1>Recent posts</h1>
    <div id='posts'>
      <%= render @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= turbo_frame_tag id='new_post' do %>
  <% if @post.errors.any? %>
    <div id="error_explaination">
      <h3>Errors:</h3>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>   
    </div>
  <% end %>

  <%= render 'post_form', post: @post %>
<% end %>

app/views/posts/show.html.erb
<h1>Post</h1>

<%= render @post %>