config/routes.rb
Rails.application.routes.draw do
  root 'landings#home'
  resources :posts, except: %i[edit update] do
    resources :likes, only: %i[index], module: 'posts'
    resources :comments, except: %i[show edit update], module: 'posts'
  end
  get 'comments/:id/likes', to: 'comments/likes#index', as: 'comment_likes'
  resources :users, only: %i[index show] do
    resources :friends, only: %i[index], controller: 'friendships'
  end
  resources :friends, only: %i[create update destroy], controller: 'friendships', as: 'friendships'
  resources :notifications, only: %i[index destroy]
  put 'notifications/:id', to: 'notifications#update_hidden', as: 'update_notification_hidden'
  post '/users/notifications-seen', to: 'users#notifications_seen'
  resources :likes, only: %i[create destroy]

  devise_for :users, path: 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                                      registrations: 'users/registrations',
                                                      sessions: 'users/sessions',
                                                      passwords: 'users/passwords' }
  devise_scope :user do
    get '/accounts/complete', to: 'users/registrations#complete_edit'
    put '/accounts/complete', to: 'users/registrations#complete_update'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-controller='scroll'>
  <head>
    <title>OdinSocial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller='notifications'>
    <section class='header'>
      <%= link_to 'Odin Social', root_path, class: 'header-logo' %>
      <% if user_signed_in? %>
        <div class='nav-notification-and-links' data-controller='menu'>
          <% if unseen_notifications %>
            <%= form_with url: users_notifications_seen_path, method: 'post' do |form| %>
              <%= form.button do %>
                <span class="material-symbols-outlined notification-symbol notifications-unread" tabindex='0' 
                      data-action='click->notifications#toggle keydown.enter->notifications#toggle click->notifications#updateSeen keydown.enter->notifications#updateSeen'
                      data-notifications-target='symbol'>
                      Notifications Unread
                </span>
              <% end %>
            <% end %>
          <% else %>
            <%= form_with url: users_notifications_seen_path, method: 'post' do |form| %>
              <%= form.button do %>
                <span class="material-symbols-outlined notification-symbol" tabindex='0' 
                      data-action='click->notifications#toggle keydown.enter->notifications#toggle click->notifications#updateSeen keydown.enter->notifications#updateSeen'
                      data-notifications-target='symbol'>
                      Notifications
                </span>
              <% end %>
            <% end %>
          <% end %>
          <ul class='header-links' data-menu-target='menu'>
            <li><%= link_to 'Posts', posts_path %></li>
            <li><%= link_to 'My profile', current_user %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: 'delete' } %></li>
          </ul>
          <span class="material-symbols-outlined menu-symbol" tabindex='0'
                data-action='click->menu#toggle keydown.enter->menu#toggle'
                data-notifications-target='menu'>
            menu
          </span>
        </div>
      <% else %>
        <ul class="header-links">
          <li><%= link_to 'Sign in', posts_path, class: 'sign-in' %></li>
        </ul>
      <% end %>
    </section>
    <% if user_signed_in? %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name unless msg.blank? %>
      <% end %>
      <div class='notifications' data-notifications-target='notifications'>
        <div class='notifications-title-close'>
          <span class="material-symbols-outlined close-symbol" tabindex='0' 
                  data-action='click->notifications#toggle keydown.enter->notifications#toggle'>
                  x
          </span>
        </div>
        <h2>Recent notifications</h2>
        <% recent_notifications.each do |n| %>
          <%= render '/notifications/recent_notification', n: n %>
        <% end %>
        <div class='all-notifications-link'>
          <%= link_to 'All notifications', notifications_path %>
        </div>
      </div>
    <% end %>
    
    <section class="main">
      <%= yield %>
    </section>
    <section class="footer">
      <p class="logo">Odin Social</p>
      <div>&copy; 2024 <%= link_to 'Hadayxinchao', 'https://github.com/Hadayxinchao' %></div>
    </section>
  </body>
</html>